### ISSUE TITLE
Get in touch section in "Contact Us" form needs to update

### ISSUE THREAD

**Issue by Sunny-unik** [TechNodes2-0/TechNode-Community-Website#10]
![Form image](https://github.com/TechNodes2-0/TechNode-Community-Website/assets/65410458/c1887b06-93b6-4df6-84fa-6c6b358da59f)

In the `Get in Touch` section address field is mentioned which is not part of the `Contact Us` form and the form's labels should not be black.

TODOs: 
 -  `Get in Touch` content needs to be updated
 -  Update the color of the labels
 
Steps:
 *  Fork this repository then clone the forked repository.
 *  Create a separate branch and make necessary changes.
 *  Generate PR on the main repository (don't forget to link issue)

**Comment by samara6855** [comment]
I have made the necessary changes, Please refer to the PR #12

**Comment by Nishitbaria** [comment]
Hey @samara6855 Thank you for your contribution ✨
