### ISSUE TITLE
Text is not visible in Contact us  form ✨

### ISSUE THREAD

**Issue by Nishitbaria** [TechNodes2-0/TechNode-Community-Website#16]
![image](https://github.com/TechNodes2-0/TechNode-Community-Website/assets/85815172/dea3e130-955b-4836-8ebc-ad0bc67588e8)

**Comment by jainam-panchal** [comment]
I can work on this issue.

**Comment by jainam-panchal** [comment]
#17 #

**Comment by jainam-panchal** [comment]
#17
