### ISSUE TITLE
Redesign Event Cards

### ISSUE THREAD

**Issue by Yash636261** [TechNodes2-0/TechNode-Community-Website#7]
![image](https://github.com/TechNodes2-0/TechNode-Community-Website/assets/98970491/b7ade6a4-52fa-43fa-8f29-e392fa97219e)

**Comment by killerkc12** [comment]
@Nishitbaria @Yash636261 I would like to work on this.

**Comment by Yash636261** [comment]
you can start working on it @killerkc12 .
